// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD663gouotc2IHMLH1F09pQSrIUNLrWFtg',
    appId: '1:3586186148:web:dddec7f52f0706b2b27f31',
    messagingSenderId: '3586186148',
    projectId: 'firebase-shop-list',
    authDomain: 'fir-shop-list.firebaseapp.com',
    storageBucket: 'firebase-shop-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4sydw0D7vyVIo6k5yWse6GW7BB5j1-tg',
    appId: '1:3586186148:android:f1c9208ac58234eeb27f31',
    messagingSenderId: '3586186148',
    projectId: 'firebase-shop-list',
    storageBucket: 'firebase-shop-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVKPa9cX21rTwKbcig7FLBos94NBc678U',
    appId: '1:3586186148:ios:5f4695413b1b6cc5b27f31',
    messagingSenderId: '3586186148',
    projectId: 'firebase-shop-list',
    storageBucket: 'firebase-shop-list.appspot.com',
    iosClientId: '3586186148-0mqerbadrcq4clg39ais6cn6s5qrf5rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVKPa9cX21rTwKbcig7FLBos94NBc678U',
    appId: '1:3586186148:ios:5f4695413b1b6cc5b27f31',
    messagingSenderId: '3586186148',
    projectId: 'firebase-shop-list',
    storageBucket: 'firebase-shop-list.appspot.com',
    iosClientId: '3586186148-0mqerbadrcq4clg39ais6cn6s5qrf5rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingList',
  );
}
